import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { Poppins } from "next/font/google";
import Swal from "sweetalert2";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <AuthProvider>
        <body className="bg-gray-100">{children}</body>
      </AuthProvider>
    </html>
  );
}
